# Use the PHP 7.3 runtime by replacing "php72" below with "php73"
runtime: php73

# Defaults to "serve index.php" 
entrypoint: serve index.php

env_variables:
  APP_DEBUG: true
  LOG_CHANNEL: stderr
  APP_STORAGE: /tmp

# If your main page is index.php, comment the above entrypoint setting 
handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /img
    static_dir: img

  - url: /css
    static_dir: css

  - url: /js
    static_dir: js

  - url: /home.php
    script: auto

  - url: /login.php
    script: auto

  - url: /.*
    secure: optional
    redirect_http_response_code: 301
    script: auto