INSERT INTO FISH (id, name) VALUES (1, 'Bitterling');
INSERT INTO FISH (id, name) VALUES (2, 'Pale chub');
INSERT INTO FISH (id, name) VALUES (3, 'Crucian Carp');
INSERT INTO FISH (id, name) VALUES (4, 'Dace');
INSERT INTO FISH (id, name) VALUES (5, 'Carp');
INSERT INTO FISH (id, name) VALUES (6, 'Koi');
INSERT INTO FISH (id, name) VALUES (7, 'Goldfish');
INSERT INTO FISH (id, name) VALUES (8, 'Pop-eyed goldfish');
INSERT INTO FISH (id, name) VALUES (9, 'Ranchu goldfish');
INSERT INTO FISH (id, name) VALUES (10, 'Killifish');
INSERT INTO FISH (id, name) VALUES (11, 'Crawfish');
INSERT INTO FISH (id, name) VALUES (12, 'Soft-shelled turtle');
INSERT INTO FISH (id, name) VALUES (13, 'Snapping Turtle');
INSERT INTO FISH (id, name) VALUES (14, 'Tadpole');
INSERT INTO FISH (id, name) VALUES (15, 'Frog');
INSERT INTO FISH (id, name) VALUES (16, 'Freshwater goby');
INSERT INTO FISH (id, name) VALUES (17, 'Loach');
INSERT INTO FISH (id, name) VALUES (18, 'Catfish');
INSERT INTO FISH (id, name) VALUES (19, 'Giant snakehead');
INSERT INTO FISH (id, name) VALUES (20, 'Bluegill');
INSERT INTO FISH (id, name) VALUES (21, 'Yellow perch');
INSERT INTO FISH (id, name) VALUES (22, 'Black bass');
INSERT INTO FISH (id, name) VALUES (23, 'Tilapia');
INSERT INTO FISH (id, name) VALUES (24, 'Pike');
INSERT INTO FISH (id, name) VALUES (25, 'Pond smelt');
INSERT INTO FISH (id, name) VALUES (26, 'Sweetfish');
INSERT INTO FISH (id, name) VALUES (27, 'Cherry salmon');
INSERT INTO FISH (id, name) VALUES (28, 'Char');
INSERT INTO FISH (id, name) VALUES (29, 'Golden trout');
INSERT INTO FISH (id, name) VALUES (30, 'Stringfish');
INSERT INTO FISH (id, name) VALUES (31, 'Salmon');
INSERT INTO FISH (id, name) VALUES (32, 'King salmon');
INSERT INTO FISH (id, name) VALUES (33, 'Mitten crab');
INSERT INTO FISH (id, name) VALUES (34, 'Guppy');
INSERT INTO FISH (id, name) VALUES (35, 'Nibble fish');
INSERT INTO FISH (id, name) VALUES (36, 'Angelfish');
INSERT INTO FISH (id, name) VALUES (37, 'Betta');
INSERT INTO FISH (id, name) VALUES (38, 'Neon tetra');
INSERT INTO FISH (id, name) VALUES (39, 'Rainbowfish');
INSERT INTO FISH (id, name) VALUES (40, 'Piranha');
INSERT INTO FISH (id, name) VALUES (41, 'Arowana');
INSERT INTO FISH (id, name) VALUES (42, 'Dorado');
INSERT INTO FISH (id, name) VALUES (43, 'Gar');
INSERT INTO FISH (id, name) VALUES (44, 'Arapaima');
INSERT INTO FISH (id, name) VALUES (45, 'Saddled bichir');
INSERT INTO FISH (id, name) VALUES (46, 'Sturgeon');
INSERT INTO FISH (id, name) VALUES (47, 'Sea butterfly');
INSERT INTO FISH (id, name) VALUES (48, 'Sea horse');
INSERT INTO FISH (id, name) VALUES (49, 'Clown fish');
INSERT INTO FISH (id, name) VALUES (50, 'Surgeonfish');
INSERT INTO FISH (id, name) VALUES (51, 'Butterfly fish');
INSERT INTO FISH (id, name) VALUES (52, 'Napoleonfish');
INSERT INTO FISH (id, name) VALUES (53, 'Zebra turkeyfish');
INSERT INTO FISH (id, name) VALUES (54, 'Blowfish');
INSERT INTO FISH (id, name) VALUES (55, 'Puffer fish');
INSERT INTO FISH (id, name) VALUES (56, 'Anchovy');
INSERT INTO FISH (id, name) VALUES (57, 'Horse mackerel');
INSERT INTO FISH (id, name) VALUES (58, 'Barred knifejaw');
INSERT INTO FISH (id, name) VALUES (59, 'Sea bass');
INSERT INTO FISH (id, name) VALUES (60, 'Red snapper');
INSERT INTO FISH (id, name) VALUES (61, 'Dab');
INSERT INTO FISH (id, name) VALUES (62, 'Olive flounder');
INSERT INTO FISH (id, name) VALUES (63, 'Squid');
INSERT INTO FISH (id, name) VALUES (64, 'Moray eel');
INSERT INTO FISH (id, name) VALUES (65, 'Ribbon eel');
INSERT INTO FISH (id, name) VALUES (66, 'Tuna');
INSERT INTO FISH (id, name) VALUES (67, 'Blue marlin');
INSERT INTO FISH (id, name) VALUES (68, 'Giant trevally');
INSERT INTO FISH (id, name) VALUES (69, 'Mahi-mahi');
INSERT INTO FISH (id, name) VALUES (70, 'Ocean sunfish');
INSERT INTO FISH (id, name) VALUES (71, 'Ray');
INSERT INTO FISH (id, name) VALUES (72, 'Saw shark');
INSERT INTO FISH (id, name) VALUES (73, 'Hammerhead shark');
INSERT INTO FISH (id, name) VALUES (74, 'Great white shark');
INSERT INTO FISH (id, name) VALUES (75, 'Whale shark');
INSERT INTO FISH (id, name) VALUES (76, 'Suckerfish');
INSERT INTO FISH (id, name) VALUES (77, 'Football fish');
INSERT INTO FISH (id, name) VALUES (78, 'Oarfish');
INSERT INTO FISH (id, name) VALUES (79, 'Barreleye');
INSERT INTO FISH (id, name) VALUES (80, 'Coelacanth');